#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Chess1M Random Position Generator
===================================
Randomly samples n starting positions from the Chess1M reference table
(921,600 unique starting positions formed by independently assigning any
Chess960 back-rank to White and Black). All positions are expressed as
standard FEN and Shredder-FEN strings.

Input
-----
chess1m_sp_idn_fen_ref.csv   : Chess1M reference table (generated by
                                chess960_chess1m_reference_positions.py)

Output
------
chess1m_random_pos.csv       : n randomly sampled Chess1M starting positions

Usage
-----
    python chess1m_random_pos_gen.py [--input-dir PATH] [--output-dir PATH]

    --input-dir   Directory where chess1m_sp_idn_fen_ref.csv is located.
                  Defaults to the script's own directory.
    --output-dir  Directory where chess1m_random_pos.csv is written.
                  Defaults to the script's own directory.

Author : alpha-seven-chess
Created: 2026-06-24
"""

# %% Imports
import argparse
import logging
from pathlib import Path

import numpy as np
import pandas as pd


# %% Helpers
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Randomly sample starting positions from the Chess1M reference table."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory where chess1m_sp_idn_fen_ref.csv is located (default: script directory).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory where chess1m_random_pos.csv is written (default: script directory).",
    )
    return parser.parse_args()


# %% Main
if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  %(levelname)s  %(message)s",
        datefmt="%H:%M:%S",
    )

    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # %% 1. Load Chess1M reference table
    input_path = args.input_dir / "chess1m_sp_idn_fen_ref.csv"
    logging.info("Loading Chess1M reference table from %s...", input_path)
    df_1m = pd.read_csv(input_path)
    logging.info("Loaded. Shape: %s", df_1m.shape)

    # %% 2. Define number of runs
    while True:
        try:
            no_of_runs = int(input("Enter number of random positions to generate (positive integer): "))
            if no_of_runs > 0:
                break
            else:
                print("Input must be a positive integer greater than 0.")
        except ValueError:
            print("Invalid input. Please enter a number.")
    logging.info("Generating %d random positions...", no_of_runs)

    # %% 3. Sample random Chess1M position IDs (0-indexed, matching chess1m_sp_idn)
    df_random = pd.DataFrame({
        "chess1m_sp_idn": np.random.randint(0, 960 * 960, size=no_of_runs)
    })

    # %% Add run ID (0-indexed)
    df_random["run_id"] = range(0, len(df_random))

    # %% 4. Summary stats for sampled IDs
    logging.info("Summary stats for sampled IDs:\n%s", df_random["chess1m_sp_idn"].describe())

    # %% 5. Merge with Chess1M reference table to get FEN and flags
    df_random = df_random.merge(
        df_1m[[
            "chess1m_sp_idn",
            "chess960_scharnagl_sp_idn_white",
            "chess960_scharnagl_sp_idn_black",
            "rank_1_white",
            "rank_8_black",
            "standard_fen",
            "shredder_fen",
            "is_chess960",
            "is_classical",
        ]],
        how="inner",
        on="chess1m_sp_idn",
    )

    # %% Reorder columns
    df_random = df_random[[
        "run_id",
        "chess1m_sp_idn",
        "chess960_scharnagl_sp_idn_white",
        "chess960_scharnagl_sp_idn_black",
        "rank_1_white",
        "rank_8_black",
        "standard_fen",
        "shredder_fen",
        "is_chess960",
        "is_classical",
    ]]

    # %% Save
    output_path = args.output_dir / "chess1m_random_pos.csv"
    df_random.to_csv(output_path, index=False)
    logging.info("Saved %d positions to %s", len(df_random), output_path)

    # %% Done
    logging.info("Done.")
