#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Chess1M Valuations
==================
Runs Stockfish analysis on a set of Chess1M starting positions and saves
the results to a CSV file. Each position is evaluated for a fixed time and
the engine score, principal variation moves, and metadata are recorded.
Includes file-based logging of progress, engine results, system state, and errors.

Input
-----
chess1m_sp_idn_fen_ref.csv : Chess1M reference table (generated by
                              chess960_chess1m_reference_positions.py)
chess1m_random_pos.csv     : Chess1M starting positions to analyse. Only the FEN
                              column is used; all metadata is looked up from the
                              reference table.

Output
------
chess1m_fdr_valuations_<datestamp>_<timestamp>_<n>_runs_<hash>MB_<time>s_<model>_<threads>_threads.csv
chess1m_fdr_valuations_<datestamp>_<timestamp>_<n>_runs_<hash>MB_<time>s_<model>_<threads>_threads.log

Usage
-----
    python chess1m_valuations.py [--input-dir PATH] [--output-dir PATH] [--input-file FILENAME]

    --input-dir    Directory where input files are located (default: script directory)
    --output-dir   Directory where output files are written (default: script directory)
    --input-file   Input filename (default: chess1m_random_pos.csv)

Dependencies
------------
python-chess >= 1.11.2
pandas       >= 3.0.2
psutil
py-cpuinfo
stockfish     : binary named 'stockfish' on system PATH (e.g. /usr/local/bin/stockfish)

Author  : alpha-seven-chess
Created : 2026-06-27
"""

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------
import argparse
import logging
import shutil
import time
import traceback
from pathlib import Path
from pprint import pformat
from datetime import datetime, date
from typing import List, Tuple, Optional

import chess
import chess.engine
import pandas as pd
import psutil
import cpuinfo

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
NUMBER_OF_PV_MOVES = 6
DEFAULT_INPUT_FILE = "chess1m_random_pos.csv"
REF_FILE = "chess1m_sp_idn_fen_ref.csv"
DEFAULT_HASH_SIZE = 1024
DEFAULT_TIME_PER_VALUATION = 10

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Run Stockfish analysis on Chess1M starting positions."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory where input files are located (default: script directory).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent,
        help="Directory where output files are written (default: script directory).",
    )
    parser.add_argument(
        "--input-file",
        type=str,
        default=DEFAULT_INPUT_FILE,
        help=f"Input filename (default: {DEFAULT_INPUT_FILE}).",
    )
    return parser.parse_args()


def get_computer_model() -> str:
    """Return computer model string from DMI, or 'Unknown model' if unavailable."""
    try:
        with open('/sys/devices/virtual/dmi/id/product_name', 'r') as f:
            return f.read().strip()
    except Exception:
        return "Unknown model"


def get_positive_integer(prompt: str, default: int) -> int:
    """Prompt for a positive integer, returning default if Enter is pressed."""
    while True:
        user_input = input(f"{prompt} [{default}]: ").strip()
        if user_input == "":
            return default
        if user_input.isdigit() and int(user_input) > 0:
            return int(user_input)
        else:
            print("Error: Please enter a positive integer.")


def get_system_state() -> dict:
    """Return current RAM and CPU usage."""
    vm = psutil.virtual_memory()
    return {
        "ram_used_gb": round(vm.used / (1024 ** 3), 2),
        "ram_available_gb": round(vm.available / (1024 ** 3), 2),
        "ram_percent": vm.percent,
        "cpu_percent": psutil.cpu_percent(interval=0.1),
    }


def setup_logging(log_path: Path) -> logging.Logger:
    """Set up logging to both file (DEBUG) and console (INFO)."""
    logger = logging.getLogger("chess1m_valuations")
    logger.setLevel(logging.DEBUG)

    formatter = logging.Formatter(
        fmt="%(asctime)s  %(levelname)-8s  %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    fh = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(formatter)
    logger.addHandler(fh)

    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(formatter)
    logger.addHandler(ch)

    return logger


def get_san_moves(
    board: chess.Board,
    pv_moves: List[chess.Move],
) -> Tuple[Optional[str], ...]:
    """
    Convert up to NUMBER_OF_PV_MOVES PV moves to SAN notation.
    Pads with None if fewer moves are available.
    """
    temp_board = board.copy()
    san_moves = []

    for move in pv_moves[:NUMBER_OF_PV_MOVES]:
        san_moves.append(temp_board.san(move))
        temp_board.push(move)

    while len(san_moves) < NUMBER_OF_PV_MOVES:
        san_moves.append(None)

    return tuple(san_moves)


def analyze_fen_row(row, engine, engine_name, time_per_valuation, number_of_runs,
                    machine_ident, model, number_of_threads, hash_size,
                    valuation_batch_id, batch_start_time, logger) -> pd.Series:
    """Analyse a single Chess1M starting position and return results as a pd.Series."""

    shredder_fen = row["shredder_fen"]
    run_id = row.get("run_id")
    chess1m_sp_idn = row.get("chess1m_sp_idn")
    chess960_scharnagl_sp_idn_white = row.get("chess960_scharnagl_sp_idn_white")
    chess960_scharnagl_sp_idn_black = row.get("chess960_scharnagl_sp_idn_black")
    rank_1_white = row.get("rank_1_white")
    rank_8_black = row.get("rank_8_black")
    standard_fen = row.get("standard_fen")
    is_chess960 = row.get("is_chess960")
    is_classical = row.get("is_classical")
    timestamp = datetime.now().strftime("%H:%M:%S")
    datestamp = date.today().strftime("%Y-%m-%d")

    elapsed = round(time.time() - batch_start_time, 1)
    sys_state = get_system_state()

    logger.info(
        f"START | run_id={run_id} | {run_id+1}/{number_of_runs} | "
        f"chess1m_sp_idn={chess1m_sp_idn} | elapsed={elapsed}s | "
        f"RAM used={sys_state['ram_used_gb']}GB available={sys_state['ram_available_gb']}GB "
        f"({sys_state['ram_percent']}%) | CPU={sys_state['cpu_percent']}%"
    )
    logger.debug(f"  shredder_fen={shredder_fen}")

    info_pretty = None
    lowerbound = None
    upperbound = None

    try:
        board = chess.Board(shredder_fen, chess960=True)
        info = engine.analyse(board, chess.engine.Limit(time=time_per_valuation))
        score = info['score'].white()

        pv_moves = info.get("pv", [])[:NUMBER_OF_PV_MOVES]
        move_1, move_2, move_3, move_4, move_5, move_6 = get_san_moves(board, pv_moves)

        is_mate = score.is_mate()
        mate_in = score.mate() if is_mate else None
        cp = None if is_mate else score.score()

        if 'lowerbound' in info:
            lowerbound = info['lowerbound']
        if 'upperbound' in info:
            upperbound = info['upperbound']

        info_pretty = pformat(info)

        sys_state_end = get_system_state()
        logger.info(
            f"DONE  | run_id={run_id} | score_cp={cp} | mate_in={mate_in} | "
            f"depth={info.get('depth')} | seldepth={info.get('seldepth')} | "
            f"nodes={info.get('nodes')} | nps={info.get('nps')} | "
            f"RAM used={sys_state_end['ram_used_gb']}GB available={sys_state_end['ram_available_gb']}GB "
            f"({sys_state_end['ram_percent']}%) | CPU={sys_state_end['cpu_percent']}%"
        )

        return pd.Series({
            "valuation_batch_id": valuation_batch_id,
            "run_id": run_id,
            "datestamp": datestamp,
            "timestamp": timestamp,
            "engine_name": engine_name,
            "number_of_threads": number_of_threads,
            "hash_size": hash_size,
            "time_per_valuation": time_per_valuation,
            "number_of_runs": number_of_runs,
            "machine_ident": machine_ident,
            "model": model,
            "chess1m_sp_idn": chess1m_sp_idn,
            "chess960_scharnagl_sp_idn_white": chess960_scharnagl_sp_idn_white,
            "chess960_scharnagl_sp_idn_black": chess960_scharnagl_sp_idn_black,
            "rank_1_white": rank_1_white,
            "rank_8_black": rank_8_black,
            "standard_fen": standard_fen,
            "shredder_fen": shredder_fen,
            "is_chess960": is_chess960,
            "is_classical": is_classical,
            "score_cp": cp,
            "score_mate_in": mate_in,
            "score_is_mate": is_mate,
            "score": str(info.get("score")),
            "lowerbound": lowerbound,
            "upperbound": upperbound,
            "depth": int(info.get("depth")),
            "seldepth": int(info.get("seldepth")),
            "nodes": int(info.get("nodes")),
            "nps": int(info.get("nps")),
            "move_1": move_1,
            "move_2": move_2,
            "move_3": move_3,
            "move_4": move_4,
            "move_5": move_5,
            "move_6": move_6,
            "pv": str(info.get("pv")),
            "info_pretty": info_pretty,
            "error": None,
        })

    except Exception as e:
        sys_state_err = get_system_state()
        logger.error(
            f"ERROR | run_id={run_id} | chess1m_sp_idn={chess1m_sp_idn} | "
            f"error={str(e)} | "
            f"RAM used={sys_state_err['ram_used_gb']}GB available={sys_state_err['ram_available_gb']}GB "
            f"({sys_state_err['ram_percent']}%) | CPU={sys_state_err['cpu_percent']}%"
        )
        logger.debug(f"  Traceback:\n{traceback.format_exc()}")

        return pd.Series({
            "valuation_batch_id": valuation_batch_id,
            "run_id": run_id,
            "datestamp": datestamp,
            "timestamp": timestamp,
            "engine_name": engine_name,
            "number_of_threads": number_of_threads,
            "hash_size": hash_size,
            "time_per_valuation": time_per_valuation,
            "number_of_runs": number_of_runs,
            "machine_ident": machine_ident,
            "model": model,
            "chess1m_sp_idn": chess1m_sp_idn,
            "chess960_scharnagl_sp_idn_white": chess960_scharnagl_sp_idn_white,
            "chess960_scharnagl_sp_idn_black": chess960_scharnagl_sp_idn_black,
            "rank_1_white": rank_1_white,
            "rank_8_black": rank_8_black,
            "standard_fen": standard_fen,
            "shredder_fen": shredder_fen,
            "is_chess960": is_chess960,
            "is_classical": is_classical,
            "score_cp": None,
            "score_mate_in": None,
            "score_is_mate": None,
            "score": "ERROR",
            "lowerbound": None,
            "upperbound": None,
            "depth": None,
            "seldepth": None,
            "nodes": None,
            "nps": None,
            "move_1": None,
            "move_2": None,
            "move_3": None,
            "move_4": None,
            "move_5": None,
            "move_6": None,
            "pv": None,
            "info_pretty": info_pretty,
            "error": str(e),
        })


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":

    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Load Chess1M reference table
    ref_path = args.input_dir / REF_FILE
    if not ref_path.exists():
        raise FileNotFoundError(f"Chess1M reference table not found at {ref_path}")
    df_ref = pd.read_csv(ref_path)
    logging.info(f"Reference table loaded. Shape: {df_ref.shape}")

    # Load input positions
    input_path = args.input_dir / args.input_file
    df_input = pd.read_csv(input_path)
    logging.info(f"Input file loaded. Shape: {df_input.shape}")

    # Determine FEN column to use (prefer shredder_fen over standard_fen)
    if "shredder_fen" in df_input.columns:
        fen_col = "shredder_fen"
        ref_col = "shredder_fen"
    elif "standard_fen" in df_input.columns:
        fen_col = "standard_fen"
        ref_col = "standard_fen"
    else:
        raise ValueError("Input file must contain either 'shredder_fen' or 'standard_fen' column.")
    logging.info(f"Using FEN column: '{fen_col}'")

    # Validate FENs against reference table
    df_merged = (
        df_input[[fen_col]]
        .merge(df_ref, left_on=fen_col, right_on=ref_col, how="left", indicator=True)
    )

    invalid = df_merged[df_merged["_merge"] == "left_only"]
    n_invalid = len(invalid)
    if n_invalid > 0:
        logging.warning(f"Invalid Chess1M position FEN(s) found and skipped: {n_invalid}")
        for fen in invalid[fen_col].tolist():
            logging.warning(f"  Not a valid Chess1M starting position FEN: {fen}")

    df_valid = df_merged[df_merged["_merge"] == "both"].drop(columns=["_merge"])

    # Check for duplicates
    n_before_dedup = len(df_valid)
    df_valid = df_valid.drop_duplicates(subset=[fen_col]).reset_index(drop=True)
    n_duplicates = n_before_dedup - len(df_valid)
    if n_duplicates > 0:
        logging.warning(f"Duplicate FEN(s) removed: {n_duplicates}")

    # Summary
    df_random = df_valid.copy()
    df_random["run_id"] = range(0, len(df_random))
    number_of_runs = len(df_random)

    logging.info(f"Input FENs total    : {len(df_input)}")
    logging.info(f"Invalid FENs skipped: {n_invalid}")
    logging.info(f"Duplicates removed  : {n_duplicates}")
    logging.info(f"Unique valid FENs   : {number_of_runs}")

    if df_random.empty:
        raise ValueError("No valid Chess1M positions to analyse. Exiting.")

    # Collect machine info
    cpu_cores_physical = psutil.cpu_count(logical=False)
    cpu_cores_logical = psutil.cpu_count(logical=True)
    default_threads = max(1, cpu_cores_logical - 1)
    memory_gb = round(psutil.virtual_memory().total / (1024 ** 3), 2)
    cpu_info = cpuinfo.get_cpu_info()['brand_raw']
    model = get_computer_model()
    machine_ident = f"{model}_{cpu_info}_{cpu_cores_physical}_{cpu_cores_logical}_{memory_gb}"

    # Get user inputs
    number_of_threads = get_positive_integer("Enter number of threads for engine runs", default_threads)
    hash_size = get_positive_integer("Enter hash size in MB", DEFAULT_HASH_SIZE)
    time_per_valuation = get_positive_integer("Enter time per valuation in s", DEFAULT_TIME_PER_VALUATION)

    # Build output filenames
    datestamp = date.today().strftime("%Y-%m-%d")
    timestamp = datetime.now().strftime("%H-%M")
    base_filename = (
        f"chess1m_fdr_valuations_{datestamp}_{timestamp}_{number_of_runs}_runs_"
        f"{hash_size}MB_{time_per_valuation}s_{model}_{number_of_threads}_threads"
    )
    output_csv = args.output_dir / f"{base_filename}.csv"
    output_log = args.output_dir / f"{base_filename}.log"

    # Setup logging
    logger = setup_logging(output_log)
    logger.info("=" * 80)
    logger.info("Chess1M FDR Valuations — Batch Start")
    logger.info("=" * 80)
    logger.info(f"Valuation batch ID  : {datestamp}_{timestamp}_{number_of_runs}_{model}")
    logger.info(f"Input file          : {input_path}")
    logger.info(f"Reference file      : {ref_path}")
    logger.info(f"Output CSV          : {output_csv}")
    logger.info(f"Output log          : {output_log}")
    logger.info(f"Input FENs total    : {len(df_input)}")
    logger.info(f"Invalid FENs skipped: {n_invalid}")
    logger.info(f"Duplicates removed  : {n_duplicates}")
    logger.info(f"Unique valid FENs   : {number_of_runs}")
    logger.info(f"Machine             : {machine_ident}")
    logger.info(f"CPU cores (phys/log): {cpu_cores_physical}/{cpu_cores_logical}")
    logger.info(f"Total RAM (GB)      : {memory_gb}")
    logger.info(f"Threads             : {number_of_threads}")
    logger.info(f"Hash size (MB)      : {hash_size}")
    logger.info(f"Time per valuation  : {time_per_valuation}s")

    sys_state_start = get_system_state()
    logger.info(
        f"System state at start: RAM used={sys_state_start['ram_used_gb']}GB "
        f"available={sys_state_start['ram_available_gb']}GB "
        f"({sys_state_start['ram_percent']}%) | CPU={sys_state_start['cpu_percent']}%"
    )
    logger.info("=" * 80)

    valuation_batch_id = f"{datestamp}_{timestamp}_{number_of_runs}_{model}"

    # Initialise engine
    if not shutil.which("stockfish"):
        raise FileNotFoundError("Stockfish binary not found on PATH.")

    engine = chess.engine.SimpleEngine.popen_uci("stockfish")
    engine_name = engine.id.get("name")
    logger.info(f"Engine initialised: {engine_name}")

    engine.configure({"Threads": number_of_threads, "Hash": hash_size})
    logger.info(f"Engine configured: Threads={number_of_threads}, Hash={hash_size}MB")

    # Run analysis
    batch_start_time = time.time()
    try:
        df_results = df_random.apply(
            lambda row: analyze_fen_row(
                row, engine, engine_name, time_per_valuation, number_of_runs,
                machine_ident, model, number_of_threads, hash_size,
                valuation_batch_id, batch_start_time, logger
            ),
            axis=1,
        )
    finally:
        engine.quit()
        logger.info("Engine quit.")

    # Batch complete
    total_elapsed = round(time.time() - batch_start_time, 1)
    n_errors = df_results["error"].notna().sum()
    n_completed = number_of_runs - n_errors
    sys_state_end = get_system_state()

    logger.info("=" * 80)
    logger.info("Batch Complete")
    logger.info(f"Total elapsed       : {total_elapsed}s")
    logger.info(f"Positions completed : {n_completed}/{number_of_runs}")
    logger.info(f"Errors              : {n_errors}")
    logger.info(
        f"System state at end : RAM used={sys_state_end['ram_used_gb']}GB "
        f"available={sys_state_end['ram_available_gb']}GB "
        f"({sys_state_end['ram_percent']}%) | CPU={sys_state_end['cpu_percent']}%"
    )
    logger.info("=" * 80)

    # Save results
    df_results.to_csv(output_csv, index=False)
    logger.info(f"Results saved to {output_csv}")
    logger.info("Program ended.")
